Models/CreditCard.cs
/*
 * CreditCard.cs
 * JYTGameStore Project
 * 
 *  Revision History
 *      Tan Cuong Luong, 2021.11.05: Created
 *      Jeonghwan Ju, 2021.11.07: Updated
 */
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace JYTGameStore.Models
{
    public class CreditCard 
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Display(Name = "Number")]
        public int CreditCardId { get; set; }

        [Display(Name = "Credit Card #")]
        [Required]
        [StringLength(16, ErrorMessage = "Credit Card # Should be 16 digits")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:################}")]
        [CreditCard]
        [Range(1000000000000000, 9999999999999999, ErrorMessage = "Please check the credit card number again")]
        public string CCNumber { get;set; }

        [Display(Name = "Expiry Month")]
        [Required]
        [StringLength(2, ErrorMessage = "Expiry Month Should be 2 digits")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:##}")]
        [Range(01, 12, ErrorMessage = "Please check the month again")]
        public string CCMonth { get; set; }

        [Display(Name = "Expiry Year")]
        [Required]
        [StringLength(2, ErrorMessage = "Expiry Year Should be 2 digits")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:##}")]
        [Range(21, 99, ErrorMessage = "Please check the year again")]        
        public string CCYear { get; set; }

        [Display(Name = "PIN")]
        [Required]
        [StringLength(3, ErrorMessage = "PIN Should be 3 digits")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:###}")]
        [RegularExpression(@"^\d{3}$", ErrorMessage = "Your PIN is the 3 digits behind your card")]        
        public string CCPIN { get; set; }

        public string userId { get; set; }
        [ForeignKey("userId")]
        public virtual ApplicationUser User { get; set; }
    }
}

Controllers/CreditCardsController.cs
/*
 * CreditCardsController.cs
 * JYTGameStore Project
 * 
 *  Revision History
 *      Tan Cuong Luong, 2021.11.05: Created
 *      Jeonghwan Ju, 2021.11.07: Updated
 */
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using JYTGameStore.Data;
using JYTGameStore.Models;
using Microsoft.AspNetCore.Identity;

namespace JYTGameStore.Controllers
{
    public class CreditCardsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private SignInManager<IdentityUser> signInManager;
        private UserManager<IdentityUser> userManager;

        //Validation method
        bool ValidateCreditCardNumber(string cardNumber)
        {
            if (string.IsNullOrWhiteSpace(cardNumber))
                return false;
            System.Collections.Generic.IEnumerable<char> rev = cardNumber.Reverse();
            int sum = 0, i = 0;
            foreach (char c in rev)
            {
                if (c < '0' || c > '9')
                    return false;
                int tmp = c - '0';
                if ((i & 1) != 0)
                {
                    tmp <<= 1;
                    if (tmp > 9)
                        tmp -= 9;
                }
                sum += tmp;
                i++;
            }
            // return ((sum % 10) == 0);
            return true;        // checking only numbers
        }
        bool ValidateExpiry(int month, int inputYear)
        {
            string strYear = "20" + Convert.ToString(inputYear);
            int year = Int32.Parse(strYear);
            var DateTimeNow = DateTime.Now;
            var MonthNow = DateTimeNow.Month;
            var YearNow = DateTimeNow.Year;

            if (year >= YearNow)
            {
                if (year > YearNow)
                {
                    return true;
                }

                if (year == YearNow)
                {
                    if (month >= MonthNow)
                    {
                        return true;
                    }
                }
            }

            return false;
        }

        public CreditCardsController(ApplicationDbContext context, 
            SignInManager<IdentityUser> signInManager, UserManager<IdentityUser> userManager)
        {
            _context = context;
            this.signInManager = signInManager;
            this.userManager = userManager;
        }

        // GET: CreditCards
        public async Task<IActionResult> Index()
        {
            // getting user id
            var user = await userManager.FindByNameAsync(User.Identity.Name);
            string userId = user.Id;

            // ViewBag
            ViewBag.Title = User.Identity.Name + "'s Credit Card";

            var applicationDbContext = _context.CreditCard.Where(x => x.userId == userId).OrderBy(a => a.CreditCardId);
            var cards = await applicationDbContext.ToListAsync();            
            return View(cards.ToList());
        }

        // GET: CreditCards/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var creditCard = await _context.CreditCard
                .Include(c => c.User)
                .FirstOrDefaultAsync(m => m.CCNumber == id);
            if (creditCard == null)
            {
                return NotFound();
            }

            return View(creditCard);
        }

        // GET: CreditCards/Create
        public IActionResult Create()
        {
            // ViewBag
            ViewBag.Title = "Add New Credit Card";

            return View();
        }

        // POST: CreditCards/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CCNumber,CCMonth,CCYear,CCPIN")] CreditCard creditCard)
        {
            // getting user id
            var user = await userManager.FindByNameAsync(User.Identity.Name);
            string userId = user.Id;

            //validation
            CreditCard card = new CreditCard();
            card.CCNumber = creditCard.CCNumber;
            card.CCMonth = creditCard.CCMonth;
            card.CCYear = creditCard.CCYear;
            card.CCPIN = creditCard.CCPIN;
            card.userId = userId;

            // Validate 'Credit Card Number' and 'Expire'
            if (ValidateCreditCardNumber(card.CCNumber))
            {
                if (ValidateExpiry(int.Parse(card.CCMonth), int.Parse(card.CCYear)))
                {
                    if (ModelState.IsValid)
                    {
                        _context.Add(card);
                        await _context.SaveChangesAsync();
                        return RedirectToAction(nameof(Index));
                    }
                }
            }            
            
            return View(creditCard);
        }

        // GET: CreditCards/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // ViewBag
            ViewBag.Title = "Edit Credit Card";

            var creditCard = await _context.CreditCard.FindAsync(id);
            if (creditCard == null)
            {
                return NotFound();
            }

            // mask credit card number
            var ccNumber = "****" +
                            creditCard.CCNumber.Substring(4, 4) +
                            "****" +
                            creditCard.CCNumber.Substring(12, 4);
            creditCard.CCNumber = ccNumber;

            return View(creditCard);
        }

        // POST: CreditCards/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, [Bind("CreditCardId,CCNumber,CCMonth,CCYear,CCPIN,userId")] CreditCard creditCard)
        {
            // getting user id
            var user = await userManager.FindByNameAsync(User.Identity.Name);
            string userId = user.Id;

            //validation
            CreditCard card = new CreditCard();

            card.CreditCardId = creditCard.CreditCardId;        // PK
            card.CCNumber = creditCard.CCNumber;
            card.CCMonth = creditCard.CCMonth;
            card.CCYear = creditCard.CCYear;
            card.CCPIN = creditCard.CCPIN;
            card.userId = userId;

            // Validate 'Credit Card Number' and 'Expire'
            if (ValidateCreditCardNumber(card.CCNumber))
            {
                if (ValidateExpiry(int.Parse(card.CCMonth), int.Parse(card.CCYear)))
                {
                    if (ModelState.IsValid)
                    {
                        try
                        {
                            _context.Update(creditCard);
                            await _context.SaveChangesAsync();
                        }
                        catch (DbUpdateConcurrencyException)
                        {
                            if (!CreditCardExists(creditCard.CCNumber))
                            {
                                return NotFound();
                            }
                            else
                            {
                                throw;
                            }
                        }
                        return RedirectToAction(nameof(Index));
                    }
                }
            }

            return View(creditCard);
        }

        // GET: CreditCards/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // ViewBag
            ViewBag.Title = "Delete Credit Card";

            var creditCard = await _context.CreditCard
                .Include(c => c.User)
                .FirstOrDefaultAsync(m => m.CreditCardId == id);
            if (creditCard == null)
            {
                return NotFound();
            }

            // mask credit card number
            var ccNumber = "****" + "-" +
                            creditCard.CCNumber.Substring(4, 4) + "-" +
                            "****" + "-" +
                            creditCard.CCNumber.Substring(12, 4);
            creditCard.CCNumber = ccNumber;

            return View(creditCard);
        }

        // POST: CreditCards/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            var creditCard = await _context.CreditCard.FindAsync(id);
            _context.CreditCard.Remove(creditCard);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CreditCardExists(string id)
        {
            return _context.CreditCard.Any(e => e.CCNumber == id);
        }
    }
}

Views/CreditCards/Create.cshtml
@model JYTGameStore.Models.CreditCard

<div class="container p-3">

    <ol class="breadcrumb">
        JYTGameStore &gt; Member &gt;&nbsp;
        <span class="font-weight-bold">Credit Card</span>
    </ol>

    <h1>@ViewBag.Title</h1>
    <hr />

    <form method="post" asp-action="Create">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="row m-2">
            <div class="form-group row col-12">
                <div class="col-3 text-right">
                    <label asp-for="CCNumber" class="control-label font-weight-bold"></label>
                </div>
                <div class="col-9">
                    <input asp-for="CCNumber" class="form-control w-50" placeholder="16 digits number" />
                    <span asp-validation-for="CCNumber" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row col-12">
                <div class="col-3 text-right">
                    <label asp-for="CCMonth" class="control-label font-weight-bold"></label>
                </div>
                <div class="col-9">
                    <input asp-for="CCMonth" class="form-control w-25" placeholder="2 digits number" />
                    <span asp-validation-for="CCMonth" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row col-12">
                <div class="col-3 text-right">
                    <label asp-for="CCYear" class="control-label font-weight-bold"></label>
                </div>
                <div class="col-9">
                    <input asp-for="CCYear" class="form-control w-25" placeholder="2 digits number" />
                    <span asp-validation-for="CCYear" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row col-12">
                <div class="col-3 text-right">
                    <label asp-for="CCPIN" class="control-label font-weight-bold"></label>
                </div>
                <div class="col-9">
                    <input asp-for="CCPIN" class="form-control w-25" placeholder="3 digits number" />
                    <span asp-validation-for="CCPIN" class="text-danger"></span>
                </div>
            </div>
        </div>

        <div class="m-2">&nbsp;</div>

        <div class="row m-1">
            <div class="col-3">
                <a asp-action="Index" class="btn btn-info w-30">Back to Credit Card Lists</a>
            </div>
            <div class="col-6 text-center">
                <input type="submit" class="btn btn-primary w-auto" value="Add Credit Card" />
            </div>
            <div class="col-3">&nbsp;</div>
        </div>
        <div class="p-3"></div>

    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/CreditCards/Delete.cshtml
@model JYTGameStore.Models.CreditCard

<div class="container p-3">

    <ol class="breadcrumb">
        JYTGameStore &gt; Member &gt;&nbsp;
        <span class="font-weight-bold">Credit Card</span>
    </ol>

    <h1>@ViewBag.Title</h1>
    <hr />

    <h3>Are you sure you want to delete this credit card?</h3>
    <hr />

    <form method="post" asp-action="Delete">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="CreditCardId" />
        <input type="hidden" asp-for="userId" />

        <div class="row m-2">
            <div class="form-group row col-12">
                <div class="col-3 text-right">
                    <label asp-for="CCNumber" class="control-label font-weight-bold"></label>
                </div>
                <div class="col-9">
                    @Html.DisplayFor(model => model.CCNumber)
                </div>
            </div>
            <div class="form-group row col-12">
                <div class="col-3 text-right">
                    <label asp-for="CCMonth" class="control-label font-weight-bold"></label>
                </div>
                <div class="col-9">
                    @Html.DisplayFor(model => model.CCMonth)
                </div>
            </div>
            <div class="form-group row col-12">
                <div class="col-3 text-right">
                    <label asp-for="CCYear" class="control-label font-weight-bold"></label>
                </div>
                <div class="col-9">
                    @Html.DisplayFor(model => model.CCYear)
                </div>
            </div>
            <div class="form-group row col-12">
                <div class="col-3 text-right">
                    <label asp-for="CCPIN" class="control-label font-weight-bold"></label>
                </div>
                <div class="col-9">
                    @Html.DisplayFor(model => model.CCPIN)
                </div>
            </div>
        </div>

        <div class="m-2">&nbsp;</div>

        <div class="row m-1">
            <div class="col-3">
                <a asp-action="Index" class="btn btn-info w-30">Back to Credit Card Lists</a>
            </div>
            <div class="col-6 text-center">
                <input type="submit" class="btn btn-danger w-auto" value="Delete Credit Card" />
            </div>
            <div class="col-3">&nbsp;</div>
        </div>
        <div class="p-3"></div>

    </form>
</div>

Views/CreditCards/Details.cshtml
@model JYTGameStore.Models.CreditCard

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>CreditCard</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CCMonth)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CCMonth)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CCYear)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CCYear)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CCPIN)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CCPIN)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.CCNumber">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/CreditCards/Edit.cshtml
@model JYTGameStore.Models.CreditCard

<div class="container p-3">

    <ol class="breadcrumb">
        JYTGameStore &gt; Member &gt;&nbsp;
        <span class="font-weight-bold">Credit Card</span>
    </ol>

    <h1>@ViewBag.Title</h1>
    <hr />

    <div class="m-2">&nbsp;</div>

    <form method="post" asp-action="Edit">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="CreditCardId" />
        <input type="hidden" asp-for="userId" />

        <div class="row m-2">
            <div class="form-group row col-12">
                <div class="col-3 text-right">
                    <label asp-for="CCNumber" class="control-label font-weight-bold"></label>
                </div>
                <div class="col-9">
                    <input asp-for="CCNumber" class="form-control w-50" placeholder="16 digits number" />
                    <span asp-validation-for="CCNumber" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row col-12">
                <div class="col-3 text-right">
                    <label asp-for="CCMonth" class="control-label font-weight-bold"></label>
                </div>
                <div class="col-9">
                    <input asp-for="CCMonth" class="form-control w-25" placeholder="2 digits number" />
                    <span asp-validation-for="CCMonth" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row col-12">
                <div class="col-3 text-right">
                    <label asp-for="CCYear" class="control-label font-weight-bold"></label>
                </div>
                <div class="col-9">
                    <input asp-for="CCYear" class="form-control w-25" placeholder="2 digits number" />
                    <span asp-validation-for="CCYear" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row col-12">
                <div class="col-3 text-right">
                    <label asp-for="CCPIN" class="control-label font-weight-bold"></label>
                </div>
                <div class="col-9">
                    <input asp-for="CCPIN" class="form-control w-25" placeholder="3 digits number" />
                    <span asp-validation-for="CCPIN" class="text-danger"></span>
                </div>
            </div>
        </div>

        <div class="m-2">&nbsp;</div>

        <div class="row m-1">
            <div class="col-3">
                <a asp-action="Index" class="btn btn-info w-30">Back to Credit Card Lists</a>
            </div>
            <div class="col-6 text-center">
                <input type="submit" class="btn btn-primary w-auto" value="Save Credit Card" />
            </div>
            <div class="col-3">&nbsp;</div>
        </div>
        <div class="p-3"></div>

    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/CreditCards/Index.cshtml
@model IEnumerable<JYTGameStore.Models.CreditCard>

<div class="container p-3">

    <ol class="breadcrumb">
        JYTGameStore &gt; Member &gt;&nbsp;
        <span class="font-weight-bold">Credit Card</span>
    </ol>

    <h2>@ViewBag.Title</h2>
    <hr />

    <form method="post" asp-controller="SelectingGames" asp-action="ShowGameDetails">
        <div class="row m-1 pb-1">
            <div class="col-3">&nbsp;</div>
            <div class="col-6 text-center">&nbsp;</div>
            <div class="col-3 text-right"><a asp-controller="CreditCards" asp-action="Create" class="btn btn-primary">Add Credit Card</a></div>
        </div>

        <table class="table table-striped">
            <thead class="table-dark">
                <tr>
                    <th class="text-center">NO</th>
                    <th class="text-center">@Html.DisplayNameFor(model => model.CCNumber)</th>
                    <th class="text-center">@Html.DisplayNameFor(model => model.CCMonth)</th>
                    <th class="text-center">@Html.DisplayNameFor(model => model.CCYear)</th>
                    <th class="text-center">&nbsp;</th>
                </tr>
            </thead>
            @if (Model.Count() > 0)
            {
                var no = 0;
                <tbody>
                    @foreach (var creditCardItem in Model)
                    {
                        no++;
                        var ccNumber = "****" + "-" +
                            creditCardItem.CCNumber.Substring(4, 4) + "-" +
                            "****" + "-" +
                            creditCardItem.CCNumber.Substring(12, 4);
                        <tr>
                            <td class="text-center">@no</td>
                            <td class="text-center font-weight-bold">@ccNumber</td>
                            <td class="text-center">@creditCardItem.CCMonth</td>
                            <td class="text-center">@creditCardItem.CCYear</td>
                            <td class="text-center">
                                <a asp-controller="CreditCards" asp-action="Edit" asp-route-Id="@creditCardItem.CreditCardId" class="btn btn-info mx-1">Edit</a>
                                <a asp-controller="CreditCards" asp-action="Delete" asp-route-Id="@creditCardItem.CreditCardId" class="btn btn-danger mx-1">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
            }
            else
            {
                <tbody>
                    <tr><td colspan="5" class="text-center"><b>No Credit Card!</b></td></tr>
                </tbody>
            }
        </table>

        <div class="row m-1">
            <div class="col-3"><a asp-controller="Home" asp-action="Index" class="btn btn-secondary">Back to Home</a></div>
            <div class="col-6 text-center">&nbsp;</div>
            <div class="col-3 text-right">&nbsp;</div>
        </div>
    </form>

</div>